### ISSUE TITLE
Support for multiple chains easilly

### ISSUE THREAD

**Issue by UTkzhang** [sudoswap/sudoswap-sdk#1]
The constructor should take in a network ID and perform the query on that chain, instead of defauting to the mainnet chain. This would help integrate testing for dev envs etc.

**Comment by sudo-owen** [comment]
Yes, Goerli support will be coming soon.

**Comment by UTkzhang** [comment]
Closing with https://github.com/sudoswap/sudo-defined-quoter/commit/870918464b0a745f9606d706ce0ccb6cd8a50333
